Add alias parameter to host config
ParallelSSH/parallel-ssh pull request #355
Opened 2022-08-02 08:33 UTC by simonfelding

this is useful for weird ssh proxies like cyberark PAM. Without this, it is difficult to identify the source of the output, as they all have the same hostname.

2022-08-02 13:55 UTC, pkittenis commented
Hi there,

Thanks for the interest and the PR.

This looks like useful functionality, and your code snippet above is a good first step for config parsing too. That one might be worth a separate PR if you're interested in making one.

I left some comments on the code.

2022-08-02 14:27 UTC, simonfelding commented
Thank you! I'll make a seperate PR for parsing a ssh config file when this one gets pulled to master :) It would be useful indeed.

I don't see any comments on the code, did you use the review function on github or what?

2022-08-05 18:31 UTC, pkittenis requested changes

2022-08-06 15:51 UTC, simonfelding commented on pssh/clients/base/parallel.py
> +    def __init__(self, hosts, user=None, password=None, port=None, pkey=None, alias=None,
Makes a lot of sense, thanks. I think I got a bit tired while working on it and figuring out the code 😅

2022-08-06 18:13 UTC, simonfelding commented on tests/native/test_parallel_client.py
> +        client_aliases = [client._host_clients[idx, hosts[idx][0]].alias for idx in range(len(output))]
done!

2022-08-06 18:22 UTC, simonfelding commented
I made a single client test and it works as expected now.

It throws an error in the host config test but I think it's actually supposed to. Shouldn't a client that fails still return its parameters?

I'm not entirely sure where to fix this, maybe you can help me out here? :)

2022-08-20 09:50 UTC, pkittenis commented on pssh/clients/native/single.py
> +        :type alias: str or int
```suggestion
        :type alias: str
```

2022-08-20 09:50 UTC, pkittenis commented on pssh/clients/ssh/single.py
> +        :type alias: str or int
```suggestion
        :type alias: str
```

2022-08-20 09:50 UTC, pkittenis commented on pssh/config.py
> +        if self.alias is not None and not isinstance(self.alias, (str, int)):
```suggestion
        if self.alias is not None and not isinstance(self.alias, str):
```

2022-08-20 09:50 UTC, pkittenis commented on pssh/config.py
> +            raise ValueError("Alias %s is not a string or integer" % (self.alias,))
```suggestion
            raise ValueError("Alias %s is not a string" % (self.alias,))
```

2022-08-20 09:50 UTC, pkittenis commented on pssh/output.py
> +        :type alias: str or int
```suggestion
        :type alias: str
```

2022-08-20 09:50 UTC, pkittenis commented on tests/test_host_config.py
> +        self.assertRaises(ValueError, HostConfig, alias=2.2)
```suggestion
        self.assertRaises(ValueError, HostConfig, alias=2)
```

2022-08-20 09:56 UTC, pkittenis commented
Looks good, thank you again for the PR.

Made a small change to docstrings and accepted types for `alias` to only accept `str` types as aliases, not `int`, to be in line with SSH conventions.

2022-08-20 09:57 UTC, pkittenis approved these changes

2022-08-20 09:59 UTC, merged

2022-08-20 10:35 UTC, simonfelding commented
Brilliant! I'll commit a ssh config parser in a new PR.